### ISSUE TITLE
About the text-ui

### ISSUE THREAD

**Issue by CerberuX** [cubing/twsearch#54]
![a67384b9-e099-4c46-b72d-76728ec32e28](https://github.com/cubing/twsearch/assets/18114359/4f5bd7dd-925e-41e4-b072-6627edd177c0)
i think the Alg accept moves like "x, y, z..." instead of "Fv..." is better and easier to use. 
and the move subset don' have multiple layers move like "Rw"(or i missed?)

**Comment by lgarron** [comment]
This UI is super experimental. There isn't really anything actionable here, since the text UI exposes KPuzzle internals very directly.

We'll certainly want to think about UX for selecting rotations eventually, but that's a long while off.
